//
//  ExampleAirports.swift
//  FlightDashboard
//
//  Created by Allen Parslow on 7/15/22.
//

import Foundation

class ExampleAirportStore {
    static let airports = [
        "DAL": AirportMeta([
            "airport_code": "KDAL",
            "alternate_ident": "DAL",
            "code_icao": "KDAL",
            "code_iata": "DAL",
            "code_lid": "DAL",
            "name": "Dallas Love Fld",
            "type": "Airport",
            "city": "Dallas",
            "state": "TX",
            "timezone": "America/Chicago",
            "country_code": "US",
            "wiki_url": "http://en.wikipedia.org/wiki/Dallas_Love_Field",
            "airport_flights_url": "/airports/KDAL/flights",
        ]),
        "HOU": AirportMeta([
            "airport_code": "KHOU",
            "alternate_ident": "HOU",
            "code_icao": "KHOU",
            "code_iata": "HOU",
            "code_lid": "HOU",
            "name": "William P Hobby",
            "type": "Airport",
            "city": "Houston",
            "state": "TX",
            "timezone": "America/Chicago",
            "country_code": "US",
            "wiki_url": "http://en.wikipedia.org/wiki/William_P._Hobby_Airport",
            "airport_flights_url": "/airports/KHOU/flights"
        ]),
        "SAT": AirportMeta([
            "airport_code": "KSAT",
            "alternate_ident": "SAT",
            "code_icao": "KSAT",
            "code_iata": "SAT",
            "code_lid": "SAT",
            "name": "San Antonio Intl",
            "type": "Airport",
            "city": "San Antonio",
            "state": "TX",
            "timezone": "America/Chicago",
            "country_code": "US",
            "wiki_url": "http://en.wikipedia.org/wiki/San_Antonio_International_Airport",
            "airport_flights_url": "/airports/KSAT/flights",
        ]),
        "AUS": AirportMeta([
            "airport_code": "KAUS",
            "alternate_ident": "AUS",
            "code_icao": "KAUS",
            "code_iata": "AUS",
            "code_lid": "AUS",
            "name": "Austin-Bergstrom Intl",
            "type": "Airport",
            "city": "Austin",
            "state": "TX",
            "timezone": "America/Chicago",
            "country_code": "US",
            "wiki_url": "http://en.wikipedia.org/wiki/Austin-Bergstrom_International_Airport",
            "airport_flights_url": "/airports/KAUS/flights"
        ]),
        "DEN": AirportMeta([
            "airport_code": "KDEN",
            "alternate_ident": "DEN",
            "code_icao": "KDEN",
            "code_iata": "DEN",
            "code_lid": "DEN",
            "name": "Denver Intl",
            "type": "Airport",
            "city": "Denver",
            "state": "CO",
            "timezone": "America/Denver",
            "country_code": "US",
            "wiki_url": "http://en.wikipedia.org/wiki/Denver_International",
            "airport_flights_url": "/airports/KDEN/flights",
        ]),
        "LAS": AirportMeta([
            "airport_code": "KLAS",
            "alternate_ident": "LAS",
            "code_icao": "KLAS",
            "code_iata": "LAS",
            "code_lid": "LAS",
            "name": "Harry Reid Intl",
            "type": "Airport",
            "city": "Las Vegas",
            "state": "NV",
            "timezone": "America/Los_Angeles",
            "country_code": "US",
            "wiki_url": "http://en.wikipedia.org/wiki/McCarran_International_Airport",
            "airport_flights_url": "/airports/KLAS/flights"
        ]),
        "LAX": AirportMeta([
            "airport_code": "KLAX",
            "alternate_ident": "LAX",
            "code_icao": "KLAX",
            "code_iata": "LAX",
            "code_lid": "LAX",
            "name": "Los Angeles Intl",
            "type": "Airport",
            "city": "Los Angeles",
            "state": "CA",
            "timezone": "America/Los_Angeles",
            "country_code": "US",
            "wiki_url": "http://en.wikipedia.org/wiki/Los_Angeles_International_Airport",
            "airport_flights_url": "/airports/KLAX/flights"
        ]),
        "MIA": AirportMeta([
            "airport_code": "KMIA",
            "alternate_ident": "MIA",
            "code_icao": "KMIA",
            "code_iata": "MIA",
            "code_lid": "MIA",
            "name": "Miami Intl",
            "type": "Airport",
            "city": "Miami",
            "state": "FL",
            "timezone": "America/New_York",
            "country_code": "US",
            "wiki_url": "http://en.wikipedia.org/wiki/Miami_International",
            "airport_flights_url": "/airports/KMIA/flights"
        ]),
        "JFK": AirportMeta([
            "airport_code": "KJFK",
            "alternate_ident": "JFK",
            "code_icao": "KJFK",
            "code_iata": "JFK",
            "code_lid": "JFK",
            "name": "John F Kennedy Intl",
            "type": "Airport",
            "city": "New York",
            "state": "NY",
            "timezone": "America/New_York",
            "country_code": "US",
            "wiki_url": "http://en.wikipedia.org/wiki/John_F_Kennedy_International",
            "airport_flights_url": "/airports/KJFK/flights",
        ]),
        "PHX": AirportMeta([
            "airport_code": "KPHX",
            "alternate_ident": "PHX",
            "code_icao": "KPHX",
            "code_iata": "PHX",
            "code_lid": "PHX",
            "name": "Phoenix Sky Harbor Intl",
            "type": "Airport",
            "city": "Phoenix",
            "state": "AZ",
            "timezone": "America/Phoenix",
            "country_code": "US",
            "wiki_url": "http://en.wikipedia.org/wiki/Phoenix_Sky_Harbor_International_Airport",
            "airport_flights_url": "/airports/KPHX/flights",
        ]),
        "MEM": AirportMeta([
            "airport_code": "KMEM",
            "alternate_ident": "MEM",
            "code_icao": "KMEM",
            "code_iata": "MEM",
            "code_lid": "MEM",
            "name": "Memphis Intl",
            "type": "Airport",
            "city": "Memphis",
            "state": "TN",
            "timezone": "America/Chicago",
            "country_code": "US",
            "wiki_url": "http://en.wikipedia.org/wiki/Memphis_International_Airport",
            "airport_flights_url": "/airports/KMEM/flights"
        ]),
        "MDW": AirportMeta([
            "airport_code": "KMDW",
            "alternate_ident": "MDW",
            "code_icao": "KMDW",
            "code_iata": "MDW",
            "code_lid": "MDW",
            "name": "Chicago Midway Intl",
            "type": "Airport",
            "city": "Chicago",
            "state": "IL",
            "timezone": "America/Chicago",
            "country_code": "US",
            "wiki_url": "http://en.wikipedia.org/wiki/Chicago_Midway_International_Airport",
            "airport_flights_url": "/airports/KMDW/flights"
        ]),
        "SNA": AirportMeta([
            "airport_code": "KSNA",
            "alternate_ident": "SNA",
            "code_icao": "KSNA",
            "code_iata": "SNA",
            "code_lid": "SNA",
            "name": "John Wayne",
            "type": "Airport",
            "city": "Santa Ana",
            "state": "CA",
            "timezone": "America/Los_Angeles",
            "country_code": "US",
            "wiki_url": "http://en.wikipedia.org/wiki/John_Wayne_Airport",
            "airport_flights_url": "/airports/KSNA/flights"
        ]),
        "MCO": AirportMeta([
            "airport_code": "KMCO",
            "alternate_ident": "MCO",
            "code_icao": "KMCO",
            "code_iata": "MCO",
            "code_lid": "MCO",
            "name": "Orlando Intl",
            "type": "Airport",
            "city": "Orlando",
            "state": "FL",
            "timezone": "America/New_York",
            "country_code": "US",
            "wiki_url": "http://en.wikipedia.org/wiki/Orlando_International_Airport",
            "airport_flights_url": "/airports/KMCO/flights"
        ]),
        "FLL": AirportMeta([
            "airport_code": "KFLL",
            "alternate_ident": "FLL",
            "code_icao": "KFLL",
            "code_iata": "FLL",
            "code_lid": "FLL",
            "name": "Fort Lauderdale Intl",
            "type": "Airport",
            "city": "Fort Lauderdale",
            "state": "FL",
            "timezone": "America/New_York",
            "country_code": "US",
            "wiki_url": "http://en.wikipedia.org/wiki/Hollywood_International_Airport",
            "airport_flights_url": "/airports/KFLL/flights"
        ])
    ]
}
